### ISSUE TITLE
Смысл паттерна команда - изолировать логику команды. Поэтому лучше внутри класса Add(и других команд) сразу писать готовую логику реализации команды и не ходить в коллекшнМенеджер. Уменьшаете количество диспатчерезации. А также если у вас есть общая логика у команд вы можете ее вынести в класс Common например, и использовать в нескольких классах.

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#1]
https://github.com/pro100kamil/itmo/blob/0e04bc7c024f2569a9770326ff56e25cfe9d8ba8/labs/java/lab5/src/commands/Add.java#L25

**Comment by pro100kamil** [comment]
Вынужден не согласиться. Потому что, например, метод collectionManager'а add (не только он) у меня используется не только внутри команды. И тогда мне получается придётся дублировать код? К тому же я планировал, чтобы ответственность за работу с коллекцией полностью ложилась на collectionManager, чтобы в случае чего мне не пришлось проходиться по всем командам и там что-то менять. Общей логики было мало, поэтому не увидел смысла в таком классе.
