### ISSUE TITLE
А это что за покемон? может информацию об ошибке выводить

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#20]
https://github.com/pro100kamil/itmo/blob/fd90094d9cbe808388ee91e8da3330708f73c59b/labs/java/lab6/src/client/managers/InputManager.java#L266

**Comment by pro100kamil** [comment]
это просто перенос строки, это даже, можно сказать не ошибка, просто, например, клиент во время ввода работника прописал EXIT.
