### ISSUE TITLE
Цитаты из чистого кода Роберта Мартина:

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#24]
https://github.com/pro100kamil/itmo/blob/8471ce7a0000ad6294cc3fa240c015655e9b4216/labs/java/lab7/src/server/managers/RequestHandler.java#L22

**Comment by Vasliska1** [comment]
1) Компактность!
Первое правило: функции должны быть компактными. Второе правило: функции должны быть еще компактнее.
Желательно, чтобы длина функции не превышала 20 строк.

2) функции не должны иметь отступов более чем на два уровня. -- то есть вложенности должно быть максимально 2

**Comment by Vasliska1** [comment]
поэтому разбейте как-то этот метод. уж очень тяжело читать

**Comment by Vasliska1** [comment]
Хотя у вас вложенности 2 -- это нормально, но метод сам по себе пухлый и непонятный

**Comment by pro100kamil** [comment]
вот так: https://github.com/pro100kamil/itmo/blob/2028a9fdb9a75a6677b95efc832060b8136c29a2/labs/java/lab7/src/server/managers/RequestHandler.java#L78 ?
