### ISSUE TITLE
1) я не поняла, как этот элемент обновляется в коллекции? ну, вижу в worker новые значения устанавливаются, а как это влияет на коллекцию? 2) а с блокировкой что?

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#28]
https://github.com/pro100kamil/itmo/blob/8471ce7a0000ad6294cc3fa240c015655e9b4216/labs/java/lab7/src/server/managers/CollectionManager.java#L100

**Comment by pro100kamil** [comment]
1) ну в коллекции как раз лежит этот воркер
2) https://github.com/pro100kamil/itmo/blob/2028a9fdb9a75a6677b95efc832060b8136c29a2/labs/java/lab7/src/server/managers/BlockingCollectionManager.java#L13 - вся блокировка в этом классе
