### ISSUE TITLE
"Имена должны передавать намерения программиста" Роберт Мартин. Что за kol? это оценка за лабу?

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#29]
https://github.com/pro100kamil/itmo/blob/8471ce7a0000ad6294cc3fa240c015655e9b4216/labs/java/lab7/src/server/managers/CollectionManager.java#LL110C17-L110C21

**Comment by pro100kamil** [comment]
https://github.com/pro100kamil/itmo/blob/2028a9fdb9a75a6677b95efc832060b8136c29a2/labs/java/lab7/src/server/managers/CollectionManager.java#LL95C14-L95C14
