### ISSUE TITLE
Слушайте, ну вот так все пихать в конструктор, как-то не по канону, это возможно разбить на методы и один раз вызвать?

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#30]
https://github.com/pro100kamil/itmo/blob/8471ce7a0000ad6294cc3fa240c015655e9b4216/labs/java/lab7/src/server/managers/ServerManager.java#L27

**Comment by pro100kamil** [comment]
https://github.com/pro100kamil/itmo/blob/2028a9fdb9a75a6677b95efc832060b8136c29a2/labs/java/lab7/src/server/managers/ServerManager.java#LL27C9-L27C9
