### ISSUE TITLE
Где то console.write, где то System.out.println, надо унифицировать

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#4]
https://github.com/pro100kamil/itmo/blob/0e04bc7c024f2569a9770326ff56e25cfe9d8ba8/labs/java/lab5/src/managers/InputManager.java#L336

**Comment by pro100kamil** [comment]
Выглядит не очень да, но System.out.println я делал только в командах, где надо что-то выводить в стандартный вывод. console.write в остальных случаях.
