### ISSUE TITLE
Плохой парсер команд.

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#6]
https://github.com/pro100kamil/itmo/blob/0e04bc7c024f2569a9770326ff56e25cfe9d8ba8/labs/java/lab5/src/managers/InputManager.java#L217

**Comment by pro100kamil** [comment]
Если говорить про работоспособность, то по моим наблюдениям и наблюдениям ещё нескольких людей неплохой. Если говорить о коде, то он написан не так универсально, но хорошо читаемо.
