### ISSUE TITLE
Ощущение, что на этом методе рушится принцип единственной ответственности.

### ISSUE THREAD

**Issue by Vasliska1** [pro100kamil/itmo#7]
https://github.com/pro100kamil/itmo/blob/0e04bc7c024f2569a9770326ff56e25cfe9d8ba8/labs/java/lab5/src/managers/InputManager.java#L321

**Comment by pro100kamil** [comment]
хм, класс InputManager предназначен для работы с вводом. run - запускает как раз весь ввод
